# Generated by Django 4.2.1 on 2023-06-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('company_name', models.CharField(max_length=100)),
                ('trade_type', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('buy_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('balance_quantity', models.IntegerField(blank=True, null=True)),
                ('avg_purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('split_ratio_x', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('split_ratio_y', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
